version: '3'

services:
  strapi:
    container_name: pg_strapi
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - pg-app-data:/srv/app
    depends_on:
      - db

  db:
    container_name: pg_postgres
    image: postgres
    restart: always
    volumes:
      - pg-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi

volumes:
  pg-db-data:
  pg-app-data: